// Src/Fgj.Cqrs.React/nextjs-blog/components/footer.js
import React, { Component } from 'react';

class Footer extends Component {
    render() {
        return (
            <footer className="footer">
                <div className="container">
                    <div className="row">
                        <div className="col-12 text-center">
                            <p>Criado por Fernando José</p>
                            <p>fernandogjose@gmail.com</p>
                            <p>
                                <a href="https://github.com/fernandogjose" target="_blank">GitHub</a> |
                                <a href="https://www.linkedin.com/in/fernando-jos%C3%A9-701027158/" target="_blank">LinkedIn</a>
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        )
    }
}

export default Footer

// Src/Fgj.Cqrs.Front/angular/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  public nome: string;

  constructor() { }

  ngOnInit() {
  }
}

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <p>Criado por Fernando José</p>
        <p>fernandogjose@gmail.com</p>
      </div>
    </div>
  </div>
</footer>
